[2022-08-02 16:50:25,888] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T16:40:00+00:00 [queued]>
[2022-08-02 16:50:25,949] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: pokea.respond 2022-08-02T16:40:00+00:00 [queued]>
[2022-08-02 16:50:25,951] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 16:50:25,951] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2022-08-02 16:50:25,952] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 16:50:26,003] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): respond> on 2022-08-02T16:40:00+00:00
[2022-08-02 16:50:26,009] {standard_task_runner.py:51} INFO - Started process 481 to run task
[2022-08-02 16:50:26,016] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'pokea', 'respond', '2022-08-02T16:40:00+00:00', '--job-id', '159', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/pokea.py', '--cfg-path', '/tmp/tmpkiz6cspy']
[2022-08-02 16:50:26,030] {standard_task_runner.py:76} INFO - Job 159: Subtask respond
[2022-08-02 16:50:26,218] {logging_mixin.py:103} INFO - Running <TaskInstance: pokea.respond 2022-08-02T16:40:00+00:00 [running]> on host b4dcda255553
[2022-08-02 16:50:26,377] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=pokea
AIRFLOW_CTX_TASK_ID=respond
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T16:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-02T16:40:00+00:00
[2022-08-02 16:50:26,379] {python.py:118} INFO - Done. Returned value was: Greet Responded Again
[2022-08-02 16:50:26,478] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=pokea, task_id=respond, execution_date=20220802T164000, start_date=20220802T165025, end_date=20220802T165026
[2022-08-02 16:50:26,586] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-02 16:50:26,607] {local_task_job.py:118} INFO - Task exited with return code 0
